sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t lucasbissaro/workflow .

script:
  - docker run -e CI=true lucasbissaro/workflow npm run test 

deploy:
  provider: elasticbeanstalk
  region: 'eu-east-1'
  app: "workflow"
  env: "Workflow-env"
  bucket_name: "elasticbeanstalk-us-east-1-120022455394"
  bucket_path: "workflow"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"